version: '3.4'

services:
  ui:
    image: ui
    build:
      context: ui
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - ./ui:/src

  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile-dev
    ports:
      - 4000:4000
    volumes:
      - ./backend:/src

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 5000:5000
    volumes:
      - ./data:/db
